/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 13.0 		*/
/*  Created On : 16-џэт-2018 7:40:39 				*/
/*  DBMS       : PostgreSQL 						*/
/* ---------------------------------------------------- */

/* Drop Sequences for Autonumber Columns */

 

/* Drop Tables */

DROP TABLE IF EXISTS exercise CASCADE
;

/* Create Tables */

CREATE TABLE exercise
(
	id serial NOT NULL,
	exercise_id integer NOT NULL,
	training_id integer NOT NULL,
	approach integer NOT NULL,
	repetition integer NOT NULL,
	weigth integer NOT NULL
)
;

/* Create Primary Keys, Indexes, Uniques, Checks */

ALTER TABLE exercise ADD CONSTRAINT PK_exercises
	PRIMARY KEY (id)
;

/* Create Foreign Key Constraints */

ALTER TABLE exercise ADD CONSTRAINT FK_exercises_s_exercises
	FOREIGN KEY (exercise_id) REFERENCES exercise_data (id) ON DELETE Restrict ON UPDATE Cascade
;

ALTER TABLE exercise ADD CONSTRAINT FK_exercises_trainings
	FOREIGN KEY (training_id) REFERENCES training (id) ON DELETE Restrict ON UPDATE Cascade
;

/* Create Table Comments, Sequences for Autonumber Columns */

 