/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 13.0 		*/
/*  Created On : 15-џэт-2018 20:13:10 				*/
/*  DBMS       : PostgreSQL 						*/
/* ---------------------------------------------------- */

/* Drop Sequences for Autonumber Columns */

 

 

 

 

 

 

 

 

/* Drop Tables */

DROP TABLE IF EXISTS admin_data CASCADE
;

DROP TABLE IF EXISTS exercise CASCADE
;

DROP TABLE IF EXISTS exercise_data CASCADE
;

DROP TABLE IF EXISTS person CASCADE
;

DROP TABLE IF EXISTS sex CASCADE
;

DROP TABLE IF EXISTS state CASCADE
;

DROP TABLE IF EXISTS training CASCADE
;

DROP TABLE IF EXISTS user_data CASCADE
;

/* Create Tables */

CREATE TABLE admin_data
(
	id serial NOT NULL,
	user_id integer NOT NULL
)
;

CREATE TABLE exercise
(
	id serial NOT NULL,
	exercise_id integer NOT NULL,
	training_id integer NOT NULL,
	approach integer NOT NULL,
	repetition integer NOT NULL,
	weigth integer NOT NULL
)
;

CREATE TABLE exercise_data
(
	id serial NOT NULL,
	name varchar(100) NOT NULL
)
;

CREATE TABLE person
(
	id serial NOT NULL,
	first_name varchar(100) NOT NULL,
	last_name varchar(100) NOT NULL,
	birthday date NOT NULL,
	sex_id integer NOT NULL
)
;

CREATE TABLE sex
(
	id serial NOT NULL,
	sex varchar(50) NOT NULL
)
;

CREATE TABLE state
(
	id serial NOT NULL,
	state varchar(50) NOT NULL
)
;

CREATE TABLE training
(
	id serial NOT NULL,
	user_id integer NOT NULL,
	create_date date NOT NULL   DEFAULT NOW(),
	training_date date NOT NULL
)
;

CREATE TABLE user_data
(
	id serial NOT NULL,
	person_id integer NOT NULL,
	user_login varchar(50) NOT NULL,
	user_password varchar(50) NOT NULL,
	state_id integer NOT NULL   DEFAULT 1,
	date_reg date NOT NULL   DEFAULT NOW()
)
;

/* Create Primary Keys, Indexes, Uniques, Checks */

ALTER TABLE admin_data ADD CONSTRAINT PK_admins
	PRIMARY KEY (id)
;

ALTER TABLE admin_data 
  ADD CONSTRAINT user_id_unique UNIQUE (user_id)
;

ALTER TABLE exercise ADD CONSTRAINT PK_exercises
	PRIMARY KEY (id)
;

ALTER TABLE exercise_data ADD CONSTRAINT PK_s_exercises
	PRIMARY KEY (id)
;

ALTER TABLE exercise_data 
  ADD CONSTRAINT name_unique UNIQUE (name)
;

ALTER TABLE person ADD CONSTRAINT PK_persons
	PRIMARY KEY (id)
;

ALTER TABLE sex ADD CONSTRAINT PK_s_sex
	PRIMARY KEY (id)
;

ALTER TABLE sex 
  ADD CONSTRAINT index_sex UNIQUE (sex)
;

ALTER TABLE state ADD CONSTRAINT PK_s_state
	PRIMARY KEY (id)
;

ALTER TABLE state 
  ADD CONSTRAINT state_unique UNIQUE (state)
;

ALTER TABLE training ADD CONSTRAINT PK_trainings
	PRIMARY KEY (id)
;

ALTER TABLE user_data ADD CONSTRAINT PK_users
	PRIMARY KEY (id)
;

ALTER TABLE user_data 
  ADD CONSTRAINT login_unique UNIQUE (user_login)
;

/* Create Foreign Key Constraints */

ALTER TABLE admin_data ADD CONSTRAINT FK_admins_users
	FOREIGN KEY (user_id) REFERENCES user_data (id) ON DELETE Restrict ON UPDATE Cascade
;

ALTER TABLE exercise ADD CONSTRAINT FK_exercises_s_exercises
	FOREIGN KEY (exercise_id) REFERENCES exercise_data (id) ON DELETE Restrict ON UPDATE Cascade
;

ALTER TABLE exercise ADD CONSTRAINT FK_exercises_trainings
	FOREIGN KEY (training_id) REFERENCES training (id) ON DELETE Restrict ON UPDATE Cascade
;

ALTER TABLE person ADD CONSTRAINT FK_person_s_sex
	FOREIGN KEY (sex_id) REFERENCES sex (id) ON DELETE Restrict ON UPDATE Cascade
;

ALTER TABLE training ADD CONSTRAINT FK_trainings_users
	FOREIGN KEY (user_id) REFERENCES user_data (id) ON DELETE Restrict ON UPDATE Cascade
;

ALTER TABLE user_data ADD CONSTRAINT FK_users_persons
	FOREIGN KEY (person_id) REFERENCES person (id) ON DELETE Restrict ON UPDATE Cascade
;

ALTER TABLE user_data ADD CONSTRAINT FK_users_s_state
	FOREIGN KEY (state_id) REFERENCES state (id) ON DELETE Restrict ON UPDATE Cascade
;

/* Create Table Comments, Sequences for Autonumber Columns */

 

 

 

 

 

 

 

 
