/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 13.0 		*/
/*  Created On : 16-���-2018 7:40:40 				*/
/*  DBMS       : PostgreSQL 						*/
/* ---------------------------------------------------- */

/* Drop Sequences for Autonumber Columns */

 

/* Drop Tables */

DROP TABLE IF EXISTS sex CASCADE
;

/* Create Tables */

CREATE TABLE sex
(
	value serial NOT NULL,
	sex varchar(50) NOT NULL
)
;

/* Create Primary Keys, Indexes, Uniques, Checks */

ALTER TABLE sex ADD CONSTRAINT PK_s_sex
	PRIMARY KEY (value)
;

ALTER TABLE sex 
  ADD CONSTRAINT index_sex UNIQUE (sex)
;

/* Create Table Comments, Sequences for Autonumber Columns */

 