/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 13.0 		*/
/*  Created On : 16-џэт-2018 7:40:40 				*/
/*  DBMS       : PostgreSQL 						*/
/* ---------------------------------------------------- */

/* Drop Sequences for Autonumber Columns */

 

/* Drop Tables */

DROP TABLE IF EXISTS training CASCADE
;

/* Create Tables */

CREATE TABLE training
(
	id serial NOT NULL,
	user_id integer NOT NULL,
	create_date date NOT NULL   DEFAULT NOW(),
	training_date date NOT NULL
)
;

/* Create Primary Keys, Indexes, Uniques, Checks */

ALTER TABLE training ADD CONSTRAINT PK_trainings
	PRIMARY KEY (id)
;

/* Create Foreign Key Constraints */

ALTER TABLE training ADD CONSTRAINT FK_trainings_users
	FOREIGN KEY (user_id) REFERENCES user_data (id) ON DELETE Restrict ON UPDATE Cascade
;

/* Create Table Comments, Sequences for Autonumber Columns */

 